services:
  - type: web
    name: hostel-management-system-api
    env: node
    region: oregon    # Adjust based on the desired region, options: oregon, frankfurt, etc.
    plan: free        # Free plan for small projects
    buildCommand: 'npm install --legacy-peer-deps'  # Install dependencies
    startCommand: 'npm start'    # Start your Node.js server in production mode
    autoDeploy: true            # Enable automatic deploy on new commits
    branch: main                # Replace with the branch you want to deploy (e.g., master or main)
    healthCheckPath: '/'        # Health check endpoint (optional, change if necessary)
    disk:
      name: persistent-storage  # Optional: Persistent disk setup, not required for MongoDB
      sizeGB: 1                 # Storage size for static assets/logs (adjust as needed)
